Traceback (most recent call last):
  File "c:\users\prabh\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\prabh\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\prabh\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import numpy as np
from matplotlib import pyplot
import sklearn
import sklearn.preprocessing
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from datetime import datetime
from numpy import concatenate
import matplotlib as mpl
import os
from sklearn.preprocessing import StandardScaler
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-a162c1157e4c>[0m in [0;36m<module>[1;34m[0m
[0;32m      7[0m [1;32mimport[0m [0msklearn[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [1;32mimport[0m [0msklearn[0m[1;33m.[0m[0mpreprocessing[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mmodels[0m [1;32mimport[0m [0mSequential[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     10[0m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mlayers[0m [1;32mimport[0m [0mDense[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [1;32mfrom[0m [0mkeras[0m[1;33m.[0m[0mlayers[0m [1;32mimport[0m [0mLSTM[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'keras'
ModuleNotFoundError: No module named 'keras'

